-- 1. Create the Brands Table
create table public.brands (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  logo_url text not null
);

-- 2. Add brand_id to Products Table
alter table public.products
add column brand_id bigint references public.brands(id);

-- 3. Enable Row Level Security (RLS) on Brands
alter table public.brands enable row level security;

-- 4. Create Security Policies for Brands

-- Policy: Everyone can READ brands
create policy "Public Read Brands"
on public.brands for select
to anon
using (true);

-- Policy: Only Admins (Authenticated Users) can MODIFY brands
create policy "Admin Modify Brands"
on public.brands for all
to authenticated
using (true)
with check (true);
